site: SLM Architect

url: 
baseurl:  

collections:
  pages:
    output: true
    permalink: /:name
  jobs:
    output: true
    permalink: /jobs/:name
  cases:
    output: false
    permalink: /cases/:name
  business_cases:
    output: false
    permalink: /business_cases/:name
  projects:
    output: true
  business_projects:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
  
sass:
  style: compressed

plugins:
  - jekyll-sitemap

paginate: 7
paginate_path: "/blog/page-:num/"