basic_settings:
  site_title: SLM Architect
  favicon_image: /images/favicon.png

header_settings:
  logo_image: images/slm-logo.png
  logo_width: 110

hero_settings:
  background_image: /images/hero.png

menu_settings:
  menu_items:
    - title: 'Projects'
      url: '/projects'
    - title: 'About'
      url: '/'
#    - title: 'Jobs'
#      url: '/jobs'

footer_settings:
  logo_image: images/slm-logo.png
  logo_width: 110
  tagline: Made with ❤️

post_settings:
  grid_spacing: 10

contact_settings:
  email_address: 'laura@slmarchitect.com'
  form_action: 'https://formspree.io/f/xwkwgdyl'
  confirmation_url: '/'
  email_subject: 'Contact form submission'
  send_button_text: 'Get in touch'
  street_address: ''
  postal_code: ''
  city: ''
  country: ''

social_settings:
  facebook_url: ''
  twitter_url: ''
  instagram_url: 'https://www.instagram.com/laura_salemi_architect/'
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: ''
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: 'https://www.linkedin.com/in/laura-salemi-architect/'

color_settings:
  background_color: '#ffffff'
  background_alt_color: '#f4f5f6'
  text_dark_color: '#202224'
  text_medium_color: '#6C7A89'
  text_light_color: '#AEB3BB'
  accent_color: '#ccff33'
  border_color: '#ccff33'
  error_color: '#D64541'

font_settings:
  font_embed: '<link rel="stylesheet"  href="https://fonts.googleapis.com/css?family=Lato:400,500,700|Lato+Roboto:400,700&display=swap">'
  title_font: 'Lato, sans-serif'
  body_font: '"Lato Roboto", sans-serif'
  regular_weight: 400
  bold_weight: 700
  site_title:
    small_size: 30
    medium_size: 40
    large_size: 45
    weight: 700
    letter_spacing: -0.02
  menu:
    small_size: 30
    medium_size: 15
    large_size: 17
    weight: 600
    letter_spacing: 0
  h1:
    size: 48
    size_small: 39
    weight: 300
    line_height: 56
    line_height_small: 48
  h2:
    size: 44
    size_small: 36
    weight: 300
    line_height: 50
    line_height_small: 44
  h3:
    size: 38
    size_small: 30
    weight: 300
    line_height: 48
    line_height_small: 36
  h4:
    size: 32
    size_small: 28
    weight: 300
    line_height: 36
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 300
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 300
    letter_spacing: 0
    line_height: 1.6
  subtitle:
    size: 22
    size_small: 20
    weight_regular: 400
    weight_heavy: 500
    letter_spacing: 0.16
    letter_spacing_small: 0.2
    line_height: 32
    line_height_small: 28
  p:
    size: 18
    size_small: 17
    weight: 400
    letter_spacing: 0.04
    letter_spacing_small: 0
    line_height: 28
  p_small:
    size: 16
    size_small: 15
    weight: 400
    letter_spacing: 0
    line_height: 24
  label:
    size: 14
    small_size: 12
    weight: 500
    letter_spacing: 0.8
    small_letter_spacing: 0.5
    line_height: 16
  footnote:
    size: 13
    weight: 400
    letter_spacing: -0.04
    line_height: 12
  blockquote:
    small_size: 18
    medium_size: 20
    large_size: 22
    weight: 300
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 500
    letter_spacing: 0.4

advanced_settings:
  ajax_loading: true
  analytics_code: ''
  custom_styles: ""
  header_js: ""
  footer_js: ""